## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.4
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

sudo: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julie -e 'Pkg.clone("https://github.com/jgoldfar/SPSBase.jl.git"); Pkg.build("SPSBase");'
  - julie -e 'Pkg.clone("https://github.com/jgoldfar/SPSRunner.jl.git"); Pkg.build("SPSRunner");'
  - julia -e 'Pkg.clone(pwd()); Pkg.build("SPSInterface"); Pkg.test("SPSInterface"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SPSInterface")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SPSInterface")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
