## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - 1.4
  - nightly

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  fast_finish: true
  allow_failures:
    - julia: nightly

sudo: false

## uncomment the following lines to override the default test script
script:
  - julia -e "SPSBaseURL = \"https://github.com/jgoldfar/SPSBase.jl.git\"; if VERSION >= v\"0.7.0-DEV.5183\"; using Pkg; Pkg.activate(\".\"); Pkg.develop(PackageSpec(url=SPSBaseURL)); else Pkg.clone(SPSBaseURL); Pkg.build(\"SPSBase\"); end"
  - julia -e "VERSION < v\"0.7-\" && Pkg.clone(pwd()); VERSION >= v\"0.7.0-DEV.5183\"; using Pkg; Pkg.build(\"${JL_PKG}\")"
  - julia -e "Pkg.test(\"${JL_PKG}\"; coverage=true)'

after_success:
  # push coverage results to Coveralls
  - julia -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())"
  # push coverage results to Codecov
  - julia -e 'using Coverage; Codecov.submit(Codecov.process_folder())'
